### ISSUE TITLE
very visible chroma macroblock artifacts on some images (probably bug)

### ISSUE THREAD

**Issue by jonsneyers** [google/pik#11] opened 2017-07-27 13:33 UTC
I tried using cpik with target Butteraugli score 2.0 on some images. On some of them, the results had very visible chroma macroblock artifacts. For example this original image:
![008 png](https://user-images.githubusercontent.com/15010068/28672609-7eabf972-72e0-11e7-912b-2c02d603fc42.png)

became this after cpik/dpik:
![008 png png-pik2 0](https://user-images.githubusercontent.com/15010068/28672627-8e8f3a52-72e0-11e7-85d6-6382bddd56aa.png)

I assume this is a bug in either the encoder or decoder.

**Comment by jyrkialakuijala** [comment] 2017-07-27 13:56
Yes, this is a bug. Without looking at the code, it looks like a sign reversal (perhaps due to an overflow) in the intensity-to-blue deltas. We'll write to this bug when this is fixed.

Out of curiosity -- did you find this with SSIMULACRA or was this the first image you tried?

**Comment by jonsneyers** [comment] 2017-07-27 13:57
I looked at 20 images and 3 or 4 of them had this problem. This was the one where it was most obvious.

**Comment by jyrkialakuijala** [comment] 2017-07-30 08:07
The first attempt to reproduce this failed, this bug could be related to the undefined behavior found in other bugs. If you could upload the related .pik file, we could find out if this problem is in the decoder or in encoder, and reduce the space for bug hunting.

**Comment by jyrkialakuijala** [comment] 2017-07-31 21:38
Just a FYI, this problem happens on some compilers and not with others. We will provide a fix in a few days.

**Comment by dominikhlbg** [comment] 2017-08-01 13:08
One day before this issue open I sent a pull request with a fix for this bug. https://github.com/google/pik/pull/9

**Comment by szabadka** [comment] 2017-08-03 12:39
@jonsneyers Could you verify that the issue is fixed?

**Closed** 2017-08-03 13:59 UTC
